import { db } from '@/lib/db';
import { createEmbedding, projectEmbeddingText } from '@/lib/embeddings';
import { normalizeUrl } from '@/lib/dedup';
import { checkContent } from '@/lib/moderation';
import { storeEmbedding } from '@/lib/vector-search';
import type { ScrapedSource } from '@prisma/client';

export interface ScrapedProject { title: string; shortDescription: string; sourceUrl: string; language?: string; tags?: string[]; license?: string | null; starsCount?: number; lastCommitDate?: Date | null; }
export interface ScrapeResult { sourceId: string; sourceName: string; projectsFound: number; projectsNew: number; projectsUpdated: number; status: 'success' | 'partial' | 'failed'; error?: string; }

function text(value: string | null | undefined): string { return value?.replace(/\s+/g, ' ').trim() ?? ''; }
function absoluteUrl(url: string): string { return url.startsWith('http') ? url : `https://github.com${url}`; }

async function fetchGitHubApi(repoUrl: string): Promise<ScrapedProject | null> { const url = new URL(repoUrl); const [owner, repo] = url.pathname.split('/').filter(Boolean); if (!owner || !repo) return null; const response = await fetch(`https://api.github.com/repos/${owner}/${repo}`, { headers: { accept: 'application/vnd.github+json', 'user-agent': 'OpenSourcery' } }); if (!response.ok) return null; const data = await response.json() as { full_name?: string; name?: string; description?: string | null; html_url?: string; language?: string | null; license?: { spdx_id?: string | null } | null; stargazers_count?: number; pushed_at?: string | null; topics?: string[] }; return { title: data.name ?? data.full_name ?? repo, shortDescription: text(data.description) || `Open-source project ${data.full_name ?? repo}.`, sourceUrl: data.html_url ?? `https://github.com/${owner}/${repo}`, language: data.language ?? undefined, license: data.license?.spdx_id ?? null, starsCount: data.stargazers_count ?? 0, lastCommitDate: data.pushed_at ? new Date(data.pushed_at) : null, tags: data.topics ?? [] }; }

async function scrapeGitHubTrending(url: string): Promise<ScrapedProject[]> { const response = await fetch(`${url}${url.includes('?') ? '&' : '?'}since=weekly`, { headers: { accept: 'text/html', 'user-agent': 'OpenSourcery/1.0' } }); if (!response.ok) throw new Error(`GitHub Trending returned ${response.status}`); const html = await response.text(); const projects: ScrapedProject[] = []; const articles = html.match(/<article\b[^>]*class="[^"]*\bBox-row\b[^"]*"[\s\S]*?<\/article>/gi) ?? []; for (const article of articles.slice(0, 50)) { const repoMatch = article.match(/href="\/([^"/]+\/[^"/]+)"/); if (!repoMatch) continue; const description = text(article.match(/<p[^>]*>([\s\S]*?)<\/p>/i)?.[1]?.replace(/<[^>]+>/g, '')); const stars = Number((article.match(/href="\/[^"/]+\/[^"/]+\/stargazers"[^>]*>[\s\S]*?([\d,]+)/i)?.[1] ?? '0').replace(/,/g, '')); const language = text(article.match(/itemprop="programmingLanguage"[^>]*>\s*([^<]+)/i)?.[1]); projects.push({ title: repoMatch[1].split('/')[1], shortDescription: description || 'Trending open-source project on GitHub.', sourceUrl: `https://github.com/${repoMatch[1]}`, language: language || undefined, starsCount: stars }); } return projects; }

async function scrapeAwesome(url: string): Promise<ScrapedProject[]> { const parsed = new URL(url); const repo = await fetchGitHubApi(parsed.toString()); if (!repo) return []; const branchResponse = await fetch(`https://api.github.com/repos${parsed.pathname}`); const branchData = await branchResponse.json() as { default_branch?: string }; const branch = branchData.default_branch || 'main'; let raw = await fetch(`https://raw.githubusercontent.com${parsed.pathname}/${branch}/readme.md`); if (!raw.ok) { raw = await fetch(`https://raw.githubusercontent.com${parsed.pathname}/${branch}/README.md`); } if (!raw.ok) return []; const readme = await raw.text(); const links = [...readme.matchAll(/\[([^\]]+)\]\(https?:\/\/github\.com\/([^\s)]+)\)/g)].slice(0, 30); const projects = await Promise.all(links.map(async (match) => fetchGitHubApi(`https://github.com/${match[2].replace(/[?#].*$/, '')}`))); return projects.filter((project): project is ScrapedProject => project !== null); }

async function scrapeNpm(): Promise<ScrapedProject[]> { const response = await fetch('https://registry.npmjs.org/-/v1/search?text=framework&size=50'); if (!response.ok) throw new Error(`npm returned ${response.status}`); const data = await response.json() as { objects?: Array<{ package: { name: string; description?: string; links?: { npm?: string }; keywords?: string[]; version?: string } }> }; return (data.objects ?? []).map(({ package: item }) => ({ title: item.name, shortDescription: text(item.description) || `Popular npm package: ${item.name}.`, sourceUrl: item.links?.npm ?? `https://www.npmjs.com/package/${item.name}`, tags: item.keywords ?? [], language: 'JavaScript' })); }

async function scrapeGitLab(): Promise<ScrapedProject[]> { const response = await fetch('https://gitlab.com/api/v4/projects?order_by=star_count&sort=desc&per_page=30'); if (!response.ok) throw new Error(`GitLab returned ${response.status}`); const data = await response.json() as Array<{ name?: string; description?: string | null; web_url?: string; star_count?: number; last_activity_at?: string; tag_list?: string[] }>; return data.filter((item) => item.name && item.web_url).map((item) => ({ title: item.name ?? 'GitLab project', shortDescription: text(item.description) || `Popular project on GitLab.`, sourceUrl: item.web_url ?? '', starsCount: item.star_count ?? 0, lastCommitDate: item.last_activity_at ? new Date(item.last_activity_at) : null, tags: item.tag_list ?? [] })); }

async function scrapeSourceForge(url: string): Promise<ScrapedProject[]> { const response = await fetch(url, { headers: { 'user-agent': 'OpenSourcery' } }); if (!response.ok) throw new Error(`SourceForge returned ${response.status}`); const html = await response.text(); const links = Array.from(html.matchAll(/href="(https?:\/\/sourceforge\.net\/projects\/[^"/?]+)"[^>]*>([^<]*)</g)).slice(0, 30); return links.map((match) => ({ title: text(match[2]) || match[1].split('/').filter(Boolean).pop() || 'SourceForge project', shortDescription: 'Open-source project discovered on SourceForge.', sourceUrl: match[1] })); }

async function scrapeGitHubTopic(url: string): Promise<ScrapedProject[]> { const response = await fetch(url, { headers: { 'user-agent': 'OpenSourcery' } }); if (!response.ok) throw new Error(`GitHub topic returned ${response.status}`); const html = await response.text(); const links = Array.from(html.matchAll(/href="\/([^"/]+\/[^"/]+)"/g)).slice(0, 30); const projects = await Promise.all(links.map((match) => fetchGitHubApi(`https://github.com/${match[1]}`))); return projects.filter((project): project is ScrapedProject => project !== null); }

async function scrapePyPi(): Promise<ScrapedProject[]> { const response = await fetch('https://pypi.org/simple/'); if (!response.ok) throw new Error(`PyPI returned ${response.status}`); const html = await response.text(); const names = Array.from(html.matchAll(/<a[^>]*>([^<]+)<\/a>/g)).slice(0, 30).map((match) => match[1]); const results: Array<ScrapedProject | null> = await Promise.all(names.map(async (name): Promise<ScrapedProject | null> => { const metadataResponse = await fetch(`https://pypi.org/pypi/${encodeURIComponent(name)}/json`); if (!metadataResponse.ok) return null; const data = await metadataResponse.json() as { info?: { name?: string; summary?: string; license?: string; project_urls?: Record<string, string> } }; return { title: data.info?.name ?? name, shortDescription: text(data.info?.summary) || `Python package: ${name}.`, sourceUrl: `https://pypi.org/project/${name}/`, license: data.info?.license ?? null, language: 'Python', tags: [] }; })); return results.filter((project): project is ScrapedProject => project !== null); }

async function fetchProjects(source: ScrapedSource): Promise<ScrapedProject[]> { if (source.type === 'github_trending') return scrapeGitHubTrending(source.url); if (source.type === 'awesome_repo') return scrapeAwesome(source.url); if (source.type === 'github_topic') return scrapeGitHubTopic(source.url); if (source.type === 'gitlab_explore') return scrapeGitLab(); if (source.type === 'npm_top') return scrapeNpm(); if (source.type === 'pypi_top') return scrapePyPi(); if (source.type === 'sourceforge') return scrapeSourceForge(source.url); return []; }

/** Scrape one configured source, deduplicate projects, enrich embeddings, moderate, and log counts. */
export async function scrapeSource(source: ScrapedSource): Promise<ScrapeResult> { const startedAt = new Date(); let projectsFound = 0; let projectsNew = 0; let projectsUpdated = 0; try { const projects = await fetchProjects(source); projectsFound = projects.length; for (const item of projects) { const normalized = normalizeUrl(item.sourceUrl); const existing = await db.project.findUnique({ where: { sourceUrl: normalized } }); if (existing) { await db.project.update({ where: { id: existing.id }, data: { starsCount: item.starsCount, lastCommitDate: item.lastCommitDate } }); projectsUpdated += 1; continue; } const tags = item.tags ?? []; const project = await db.project.create({ data: { title: item.title, slug: `${item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}-${Math.random().toString(36).slice(2, 7)}`, shortDescription: item.shortDescription.slice(0, 280), sourceUrl: normalized, license: item.license ?? null, language: item.language ? [item.language] : [], tags, starsCount: item.starsCount ?? 0, lastCommitDate: item.lastCommitDate ?? null, moderationFlags: [], status: 'PENDING' } }); const moderation = await checkContent({ title: project.title, description: project.shortDescription, tags, sourceUrl: normalized, projectId: project.id, trustedSource: true }); if (moderation.autoApprove && process.env.OPENAI_API_KEY) { try { await storeEmbedding(project.id, await createEmbedding(projectEmbeddingText(project))); } catch { /* embedding can be generated on the next enrichment pass */ } } projectsNew += 1; } const finishedAt = new Date(); await db.scrapeLog.create({ data: { sourceId: source.id, projectsFound, projectsNew, projectsUpdated, status: 'success', startedAt, finishedAt } }); await db.scrapedSource.update({ where: { id: source.id }, data: { lastScrapedAt: finishedAt } }); return { sourceId: source.id, sourceName: source.name, projectsFound, projectsNew, projectsUpdated, status: 'success' }; } catch (error) { const message = error instanceof Error ? error.message : 'Unknown scraper error'; await db.scrapeLog.create({ data: { sourceId: source.id, projectsFound, projectsNew, projectsUpdated, status: projectsFound ? 'partial' : 'failed', error: message, startedAt, finishedAt: new Date() } }); return { sourceId: source.id, sourceName: source.name, projectsFound, projectsNew, projectsUpdated, status: projectsFound ? 'partial' : 'failed', error: message }; } }
