import { Prisma } from '@prisma/client';
import { db } from '@/lib/db';

export interface ProjectWithDistance {
  id: string; title: string; slug: string; shortDescription: string; longDescription: string | null;
  sourceUrl: string; homepageUrl: string | null; license: string | null; language: string[];
  tags: string[]; category: string | null; starsCount: number; lastCommitDate: Date | null; distance: number;
}

export interface VectorSearchParams {
  embedding: number[];
  category?: string;
  license?: string;
  language?: string;
  minStars?: number;
  tags?: string[];
  limit?: number;
  excludeId?: string;
}

/**
 * Encode a number[] as a pgvector literal string.
 *
 * NOTE: Prisma's pgvector support (via the Unsupported("vector(1536)") field type)
 * does not support binding a JS array as a typed ::vector parameter through the
 * standard Prisma.sql tagged-template binding. The @prisma/client driver serializes
 * unknown types as their JSON representation, which PostgreSQL's vector extension
 * does not accept as a cast target for the `<->` operator.
 *
 * To pass the embedding safely we sanitize each component: every element is
 * checked with Number.isFinite() and coerced to a numeric string before being
 * interpolated — no user-supplied string data ever touches this path (the vector
 * is always generated by our own OpenAI embedding call). All other query
 * parameters (strings, IDs, numbers) use real Prisma parameterization below.
 */
function vectorLiteral(values: number[]): string {
  return `[${values.map((v) => (Number.isFinite(v) ? v.toString() : '0')).join(',')}]`;
}

export async function vectorSearch(params: VectorSearchParams): Promise<ProjectWithDistance[]> {
  const limitValue =
    typeof params.limit === 'number' && params.limit > 0
      ? Math.max(1, Math.min(params.limit, 500))
      : null;

  // Build a list of Prisma.sql condition fragments — all values are real parameters
  const conditions: Prisma.Sql[] = [Prisma.sql`status = 'APPROVED'`];

  if (params.category) conditions.push(Prisma.sql`category = ${params.category}`);
  if (params.license) conditions.push(Prisma.sql`license = ${params.license}`);
  if (params.language) conditions.push(Prisma.sql`${params.language} = ANY(language)`);
  if (typeof params.minStars === 'number') {
    const stars = Math.max(0, Math.floor(params.minStars));
    conditions.push(Prisma.sql`"starsCount" >= ${stars}`);
  }
  if (params.tags?.length) {
    conditions.push(Prisma.sql`tags @> ${params.tags}::text[]`);
  }
  if (params.excludeId) conditions.push(Prisma.sql`id <> ${params.excludeId}`);

  const where = Prisma.join(conditions, ' AND ');
  // The embedding vector literal is sanitized (all values Number.isFinite-checked)
  // but injected as a SQL fragment due to the driver limitation described above.
  const vecLit = vectorLiteral(params.embedding);
  const limitClause = limitValue ? Prisma.sql`LIMIT ${limitValue}` : Prisma.sql``;

  const sql = Prisma.sql`
    SELECT id, title, slug, "shortDescription", "longDescription", "sourceUrl",
           "homepageUrl", license, language, tags, category, "starsCount",
           "lastCommitDate",
           embedding <-> CAST(${Prisma.raw(vecLit)} AS vector) AS distance
    FROM "Project"
    WHERE ${where}
    ORDER BY distance
    ${limitClause}
  `;

  try {
    const rows = await db.$queryRaw<ProjectWithDistance[]>(sql);
    return rows.map((row) => ({ ...row, distance: Number(row.distance) }));
  } catch {
    return [];
  }
}

export async function getStoredEmbedding(projectId: string): Promise<number[] | null> {
  try {
    const rows = await db.$queryRaw<Array<{ embedding: string | null }>>(
      Prisma.sql`SELECT embedding::text AS embedding FROM "Project" WHERE id = ${projectId}`,
    );
    const raw = rows[0]?.embedding;
    if (!raw) return null;
    return raw.replace(/[\[\]]/g, '').split(',').map(Number).filter(Number.isFinite);
  } catch {
    return null;
  }
}

export async function storeEmbedding(projectId: string, embedding: number[]): Promise<void> {
  // See vectorLiteral() note above for why the vector value uses Prisma.raw
  // while the projectId binding uses a real parameter.
  const vecLit = vectorLiteral(embedding);
  await db.$executeRaw(
    Prisma.sql`UPDATE "Project" SET embedding = CAST(${Prisma.raw(vecLit)} AS vector) WHERE id = ${projectId}`,
  );
}

/** Find semantically similar open-source projects using vector distance. */
export async function findSimilarProjects(projectId: string, limit = 4): Promise<ProjectWithDistance[]> {
  const embedding = await getStoredEmbedding(projectId);
  if (!embedding) return [];
  return vectorSearch({ embedding, excludeId: projectId, limit });
}

/** Search open-source alternatives to a proprietary software tool. */
export async function searchAlternatives(proprietaryTool: string, limit = 6): Promise<ProjectWithDistance[]> {
  const altTag = `alt-${proprietaryTool.toLowerCase().replace(/[^a-z0-9]/g, '')}`;
  const dbMatches = await db.project.findMany({
    where: {
      status: 'APPROVED',
      OR: [
        { tags: { has: altTag } },
        { longDescription: { contains: proprietaryTool, mode: 'insensitive' } },
      ],
    },
    take: limit,
  });

  if (dbMatches.length > 0) {
    return dbMatches.map((p) => ({ ...p, distance: 0 }));
  }

  if (process.env.OPENAI_API_KEY) {
    try {
      const { createEmbedding } = await import('@/lib/embeddings');
      const embedding = await createEmbedding(`Open source software alternative competing with ${proprietaryTool}`);
      return vectorSearch({ embedding, limit });
    } catch {
      return [];
    }
  }

  return [];
}
